# Generated by Django 5.0.4 on 2024-04-17 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_remove_product_packing_cost_remove_product_tax"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=50)),
                ("country", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("zipcode", models.IntegerField()),
                ("total_amount", models.CharField(max_length=100)),
                ("payment_method", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        default=None,
                        max_length=250,
                        null=True,
                        upload_to="images/order_image",
                    ),
                ),
                ("quantity", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("total", models.CharField(max_length=1000)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.order"
                    ),
                ),
            ],
        ),
    ]
