# Generated by Django 5.0.4 on 2024-04-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
