# Generated by Django 5.0.4 on 2024-04-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatagoryItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(default="", max_length=50)),
                ("offer", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        default=None, max_length=250, null=True, upload_to="images/"
                    ),
                ),
            ],
        ),
    ]
