# Generated by Django 5.0.4 on 2024-04-17 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_product_packing_cost_product_tax"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="packing_cost",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tax",
        ),
    ]
